services:
  - type: web
    name: autofleetx
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn Car_Rental_System.wsgi:application"
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        sync: false
      - key: DEBUG
        sync: false
      - key: ALLOWED_HOSTS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
