# Generated by Django 5.2 on 2025-04-27 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_car_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='model_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
