# Generated by Django 5.2 on 2025-05-02 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_contactmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='pin_code',
        ),
    ]
