# Generated by Django 5.2 on 2025-05-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_remove_customuser_pin_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='car_images/'),
        ),
    ]
