# Generated by Django 5.2 on 2025-05-16 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_alter_car_image_alter_customuser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='rent_per_day',
            field=models.PositiveIntegerField(),
        ),
    ]
