# Generated by Django 5.2 on 2025-05-17 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_alter_car_rent_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='rental',
            name='returned_early',
            field=models.BooleanField(default=False),
        ),
    ]
