# Generated by Django 5.2 on 2025-06-28 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_alter_rental_end_date_alter_rental_start_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rental',
            old_name='end_date',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='rental',
            old_name='start_date',
            new_name='start_datetime',
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['start_datetime'], name='main_app_re_start_d_ba5375_idx'),
        ),
        migrations.AddIndex(
            model_name='rental',
            index=models.Index(fields=['end_datetime'], name='main_app_re_end_dat_db814b_idx'),
        ),
    ]
