# Generated by Django 5.2 on 2025-06-30 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0012_rename_end_date_rental_end_datetime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('city', 'City Car'), ('electric', 'Electric Car'), ('premium', 'Premium Cars'), ('car', 'Cars'), ('van and trucks', 'Van And Trucks')], default='city', max_length=20),
        ),
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='static/images/default.jpg', upload_to='car_images/'),
        ),
    ]
