# Generated by Django 5.2 on 2025-07-03 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0013_car_vehicle_type_alter_car_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('CITY CAR', 'City Car'), ('ELECTRIC CAR', 'Electric Car'), ('PREMIUM CAR', 'Premium Cars'), ('ALL CARS', 'Cars'), ('VANS AND TRUCKS', 'Van And Trucks')], default='city', max_length=20),
        ),
    ]
