# Generated by Django 5.2 on 2025-07-03 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0014_alter_car_image_alter_car_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('CITY CAR', 'City Car'), ('ELECTRIC CAR', 'Electric Car'), ('PREMIUM CAR', 'Premium Cars'), ('ALL CARS', 'Cars'), ('VANS AND TRUCKS', 'Van And Trucks')], default='CITY CAR', max_length=20),
        ),
    ]
