# Generated by Django 5.2 on 2025-07-13 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0015_alter_car_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='image',
            field=models.ImageField(default='../static/images/default.png', upload_to='car_images/'),
        ),
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('CITY CAR', 'City Car'), ('ELECTRIC CAR', 'Electric'), ('PREMIUM', 'Premium'), ('VANS AND TRUCKS', 'Van OR Truck')], default='CITY CAR', max_length=20),
        ),
    ]
