# Generated by Django 5.2 on 2025-07-28 15:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0017_car_added_by_car_former_admin_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='date_added',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
