# Generated by Django 5.2 on 2025-07-28 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0019_alter_car_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='accident_history',
            field=models.BooleanField(choices=[(True, 'Yes — Accident Reported'), (False, 'No — Clean Record')], default=False),
        ),
    ]
