# Generated by Django 5.2 on 2025-07-28 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0020_car_accident_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='vehicle_type',
            field=models.CharField(choices=[('City Car', 'CITY CAR'), ('Electric', 'ELECTRIC CAR'), ('Premium', 'PREMIUM'), ('Van OR Truck', 'VANS AND TRUCKS')], default='City Car', max_length=20),
        ),
    ]
