# Generated by Django 5.2 on 2025-08-01 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0021_alter_car_vehicle_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.TextField(default=None),
            preserve_default=False,
        ),
    ]
